### PR TITLE
Scheduler fixes for airflow on kubernetes

### PR DESCRIPTION
**Pull request by jzucker2**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by dimberman** [comment]
@jzucker2 the minikube instantiation is still failing. Not sure what's going on there...

**Comment by jzucker2** [comment]
@dimberman seems like it's still the same issue:
```
------- Running kubectl get pods -------
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Will look into it on Monday

**Comment by dimberman** [comment]
I was able to get all the unit tests to pass on my machine, but there seems to be something funky with the new minikube and pining the server. Will investigate further.

**Comment by jzucker2** [comment]
@dimberman instead of pinning k8s versions, it might be better to just pin minikube versions and matching the version of k8s to that version of minikube

**Comment by dimberman** [comment]
@jzucker2 I have the minikube set up working. Will commit later tonight.

**Comment by jzucker2** [comment]
@dimberman sounds good. Planning on working on some helm charts later this week

**Comment by dimberman** [comment]
@jzucker2 I'm gonna close this PR because I merged the other PR which contains all your commits + the new minikube script. Thanks again for finding these fixes and yeah let's try to get that helm chart ASAP cuz people are gonna wanna try this out once it's upstreamed :).

**Pull request closed without merging**
