### PR TITLE
Support gcp_service_account_key in executor_config

### PR DESCRIPTION
**Pull request by fenglu-g**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
Support gcp_service_account_key in executor_config and update corresponding pod annotations needed by service account initializer. 

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by fenglu-g** [comment]
@dimberman, @grantnicholas @benjigoldberg, PTAL, thanks.

**Comment by dimberman** [comment]
@fenglu-g It seems that these changes are breaking the build:

`[2017-11-20 07:53:18,383] {models.py:286} ERROR - Failed to import: /home/travis/build/bloomberg/airflow/airflow/example_dags/example_kubernetes_executor.py

Traceback (most recent call last):

  File "/home/travis/build/bloomberg/airflow/airflow/models.py", line 283, in process_file

    m = imp.load_source(mod_name, filepath)

  File "/home/travis/build/bloomberg/airflow/airflow/example_dags/example_kubernetes_executor.py", line 18, in <module>

    from airflow.contrib.executors.kubernetes_executor import KubernetesExecutorConfig

  File "/home/travis/build/bloomberg/airflow/airflow/contrib/executors/kubernetes_executor.py", line 51

    "limit_cpu={}, gcp_service_account_key={})".format(

    ^

IndentationError: unexpected indent`

**Comment by dimberman** [comment]
otherwise LGTM

**Comment by grantnicholas** [comment]
Same with @dimberman, changeset looks good just make sure the build passes.

**Comment by fenglu-g** [comment]
updated, PTAL, local travis run passed 

screen shot 2017-11-28 at 10 34 34 am

**Comment by dimberman** [comment]
@fenglu-g for some reason you're not running the kubernetes tests. There should be 8 tests.

**Comment by dimberman** [comment]
@fenglu-g oh wait, just checked your travis and everything passes. Have you pulled from airflow-kubernetes-executor recently?

**Comment by fenglu-g** [comment]
@dimberman I pulled from the airflow-kubernetes-executor branch on Nov 20, not sure how recent that is though.

**Comment by dimberman** [comment]
@fenglu-g I'd pull and see if it's up-to-date.

**Comment by grantnicholas** [comment]
It looks like a license issue. There are two files that seem to be causing the issue that I *think* are generated by the dask executor and should be probably be excluded from license checks. 

```
/home/travis/build/bloomberg/airflow/dask-worker-space/global.lock
/home/travis/build/bloomberg/airflow/dask-worker-space/purge.lock)
```
These are only generated from the non-sqlite tests (as the dask executor does not work on sqlite) and thus that's why the sqlite builds pass but the mysql/postgres builds fail. 

See below for details from the error messages:

New missing licenses (11 vs 9) detected. Please correct them by adding them to to header of your files
[31mERROR: InvocationError: '/home/travis/build/bloomberg/airflow/scripts/ci/check-license.sh'[0m

(bad)
 !????? /home/travis/build/bloomberg/airflow/rat-results.txt
 !????? /home/travis/build/bloomberg/airflow/airflow/git_version
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/index.html
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.ba-throttle-debounce.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.hotkeys.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.isonscreen.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.tablesorter.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/status.json
 !????? /home/travis/build/bloomberg/airflow/dask-worker-space/global.lock
 !????? /home/travis/build/bloomberg/airflow/dask-worker-space/purge.lock

(good)
Could not find Apache license headers in the following files:
 !????? /home/travis/build/bloomberg/airflow/rat-results.txt
 !????? /home/travis/build/bloomberg/airflow/airflow/git_version
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/index.html
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.ba-throttle-debounce.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.hotkeys.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.isonscreen.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/jquery.tablesorter.min.js
 !????? /home/travis/build/bloomberg/airflow/airflow/www/static/coverage/status.json

**Comment by grantnicholas** [comment]
For how to fix it, this is a bug introduced by airflow and dask (not us). @dimberman can you merge airflow into this fork again?

**Comment by grantnicholas** [comment]
I think this was fixed in upstream airflow (I see @dimberman merged airflow into this branch and they correctly excluded the *.lock files). @fenglu-g Can you just retrigger this PR build one last time just to make sure everything is good now?

**Comment by dimberman** [comment]
hey @fenglu-g! could you please rebase to the new version of the branch and make sure everything still works? I should have all the travis tests passing by tomorrow and we can start to wrap up before  upstream merge :).

**Comment by fenglu-g** [comment]
@dimberman, will do!

**Comment by dimberman** [comment]
Awesome thanks @fenglu-g! There's a change you might end up needing to recreate your changes (since I basically rebuilt the entire git-history from scratch :P) but if you need any help on that feel free to reach out.

**Pull request closed without merging**
